removing instruction number 12
zinns/terminal-course pull request #16
Opened 2023-12-17 05:57 UTC by davidTocineta

## Pull Request Title

Brief description about what this PR does and [which ISSUE-### is closed](https://link-to-your-ticket)

## Implementation

## Screenshots

|         | before | after |
| ------- | ------ | ----- |
| desktop |        |       |
| mobile  |        |       |

**Steps to reproduce:**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

A clear and concise description of what you expected to happen.

2023-12-18 19:16 UTC, eamzea requested changes
# Changes needed / Cambios requeridos

- Improve PR description / Mejorar la descripción de la PR
- Add labels to PR / Agregar etiquetas al PR
- Add Project to PR / Agregar projecto al PR
- Link issue with PR / Enlazar tarea al PR

# Comments for future tasks / Comentarios para tareas futuras
- Commit "fix(remove)removing instruction number 12" -> should be "fix(instructions): removing instruction number 12"

2023-12-21 03:57 UTC, abrilmunozc commented on images/README.md
> +12.
Identation

2023-12-21 03:58 UTC, abrilmunozc commented on images/README.md
> +12.
you only remove de instruction but not the number

2023-12-21 04:00 UTC, abrilmunozc requested changes
You only removed the instruction but not the number 12

2024-03-19 19:52 UTC, closed without merging